# --- MySQL Connection ---
spring.datasource.url=mysql://avnadmin:AVNS_VHd2yUobkESaI6Ug-Jo@mysql-fennecgo-taganas2002-4a0c.l.aivencloud.com:23785/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_VHd2yUobkESaI6Ug-Jo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# JWT or other app properties
bezkoder.app.jwtSecret=====================BezKoder=Spring===========================
bezkoder.app.jwtExpirationMs=86400000

# File upload limit
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
